[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/nikooo777/ytdl"

[[constraint]]
  branch = "master"
  name = "github.com/lbryio/lbryschema.go"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/shopspring/decimal"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/ybbus/jsonrpc"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/bencode"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/go-ini/ini"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcutil"
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.10.51"
